<a href="https://colab.research.google.com/github/siva41/107-2-Multimedia/blob/master/Class2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.array([1,3,6,9])
b = np.linspace(0,15,4)
b

array([ 0.,  5., 10., 15.])

In [5]:
c = a-b
c

array([ 1., -2., -4., -6.])

In [6]:
a**2

array([ 1,  9, 36, 81])

In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
np.linalg.inv(a)

LinAlgError: ignored

In [10]:

a2= np.array([[1., 2.], [3., 4.]])
np.linalg.inv(a2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
a3 = np.array([[3,1], [1,2]])
b = np.array([9,8])
#3 * x0 + x1 = 9
#x0 + 2 * x1 = 8
x = np.linalg.solve(a3, b)
x

array([2., 3.])

In [12]:
c = np.random.rand(3,3)
c

array([[0.16032966, 0.21118345, 0.77922845],
       [0.36016897, 0.39496649, 0.42452422],
       [0.34657632, 0.73203185, 0.758099  ]])

In [13]:
np.dot(a,c)

array([[ 1.92039654,  3.19721198,  3.9025739 ],
       [ 4.52162138,  7.21175734,  9.78812892],
       [ 7.12284621, 11.22630271, 15.67368394]])

In [14]:
z = np.zeros((2,4),np.uint8)
type(z)

numpy.ndarray

In [15]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [16]:

o = np.ones((2,4),np.int32)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [17]:
m = np.array([[4,12,3,1],[10,12,14,29]],np.float32)
m

array([[ 4., 12.,  3.,  1.],
       [10., 12., 14., 29.]], dtype=float32)

In [18]:
m.shape

(2, 4)

In [19]:
m.dtype

dtype('float32')

In [20]:

m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]]], dtype=float32)

In [0]:
m = np.array([[14,12,3,1],[10,12,114,29],[67,23,534,2]],np.float32)

In [22]:
m[1,3]

29.0

In [23]:

m[2,:]

array([ 67.,  23., 534.,   2.], dtype=float32)

In [24]:

m[:,3]

array([ 1., 29.,  2.], dtype=float32)

In [25]:
m[0:2,1:3]

array([[ 12.,   3.],
       [ 12., 114.]], dtype=float32)

In [26]:

m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]],[[11,12,43,32],[1,5,10,23]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]],

       [[11., 12., 43., 32.],
        [ 1.,  5., 10., 23.]]], dtype=float32)

In [27]:

m[:,:,0]

array([[ 1.,  5.],
       [10., 15.],
       [11.,  1.]], dtype=float32)

In [28]:
m[0,:,:]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [29]:
src1 = np.array([[23,123,90],[100,250,0]],np.uint8)
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src1 + src2
dst

array([[148,  17, 150],
       [200,   4,  40]], dtype=uint8)

In [30]:
src2 = np.array([[125,150,60],[100,10,40]],np.float32)
dst = src1 + src2
dst

array([[148., 273., 150.],
       [200., 260.,  40.]], dtype=float32)

In [31]:
import cv2
dst = cv2.add(src1, src2, dtype=cv2.CV_32F)
dst

array([[148., 273., 150.],
       [200., 260.,  40.]], dtype=float32)

In [32]:
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src1 - src2
dst

array([[154, 229,  30],
       [  0, 240, 216]], dtype=uint8)

In [33]:
src2 = np.array([[125,150,60],[100,10,40]],np.float32)
dst = src1 * src2
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [34]:

dst = np.multiply(src1, src2)
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [35]:
src2 = np.array([[125,150,60],[100,10,40]],np.uint8)
dst = src2 / src1
dst

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[5.43478261, 1.2195122 , 0.66666667],
       [1.        , 0.04      ,        inf]])

In [36]:
3/2

1.5

In [37]:
src3 = np.array([[1,2,3],[4,5,6]],np.uint8)
src4 = np.array([[6,5],[4,3],[2,1]],np.uint8)
dst = np.dot(src3, src4)
dst

array([[20, 14],
       [56, 41]], dtype=uint8)

In [38]:

src5 = np.array([[6,5],[4,3]],np.uint8)
dst2 = np.log(src5)
dst2.dtype

dtype('float16')

In [39]:
dst2

array([[1.792, 1.609],
       [1.387, 1.099]], dtype=float16)

In [40]:
src = np.array([[30,40],[10,100]],np.uint8)
dst1 = np.power(src,2)
dst1

array([[132,  64],
       [100,  16]], dtype=uint8)

In [41]:
dst2.dtype

dtype('float16')